version: "4"
services:
  properties:
    build:
      context: packages/properties/
      dockerfile: Dockerfile
    container_name: imagine_properties
    env_file: packages/properties/.env
    ports:
      - "3000:3000"
  likes:
    build:
      context: packages/likes/
      dockerfile: Dockerfile
    container_name: imagine_likes
    env_file: packages/likes/.env
    ports:
      - "3001:3001"
  # interface:
  #   build:
  #     context: packages/interface
  #     dockerfile: Dockerfile
  #   container_name: imagine_interface
  #   env_file: packages/interface/.env
  #   ports:
  #     - "3000"