version: "4"
services:
  properties:
    build:
      context: .
      dockerfile: packages/properties/Dockerfile
    container_name: imagine_properties
    env_file: packages/properties/.env
    ports:
      - "3000"
  likes:
    build:
      context: .
      dockerfile: packages/likes/Dockerfile
    container_name: imagine_likes
    env_file: packages/likes/.env
    ports:
      - "3000"
  interface:
    build:
      context: .
      dockerfile: packages/interface/Dockerfile
    container_name: imagine_interface
    env_file: packages/interface/.env
    ports:
      - "3000"